### ISSUE TITLE
Changes required for the Python base app

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-welcome#3]
Some notes to work through:

1. The app should use a **headerbar** to match GNOME 3 style
2. The app should work slightly differently between live CD mode and installed mode. Software button should be displayed on installed mode. Install button should be displayed on "live mode".
3. Worried that antegros base uses the obsolete `webkit`. :worried: Should be at least using `webkit2`.  Need to have a look at this.
4. Do we really need to use simple-json module? Seems to be an unnecessary dependency. :confused: Coz, json should already been installed. Need to check this.
5. Various hard-coded "antegros" statements in the python code. Need to replace these.

**Comment by niyasc** [comment]
1. Removed window border which includes **title bar** and added close button to application header.
2. App is able to distinguish live cd and installed mode and work differently.
3. Migrated to **WebKit2**
4. Removed **simple-json** dependency.
5. Replaced all hard code "antergos", and "Ubuntu MATE" which was added at later stage.

**Comment by HEXcube** [comment]
That's really amazing work you did on the app Niyas! :+1:  :relaxed:
