### ISSUE TITLE
Show the budgie-remix logo in the system Details screen

### ISSUE THREAD

**Issue by Udara-U3** [budgie-remix/budgie-remix-welcome#5]
We need help to fix **A small C based patch which is required to allow us to show the budgie-remix logo in the system Details screen**. At the moment, it is hard-coded with the Ubuntu GNOME logo.

![budgie-remix_system](https://cloud.githubusercontent.com/assets/12265797/15984585/c47b2f68-2fd9-11e6-9670-f6aa93e3f918.jpg)

**Comment by HEXcube** [comment]
Closed here coz it doesn't belong to this repo. Moved to the relevant repo: [budgie-desktop-environment](https://github.com/budgie-remix/budgie-desktop-environment/issues/17/) :relaxed:
