### ISSUE TITLE
hide "show this dialog" option on live CD

### ISSUE THREAD

**Issue by fossfreedom** [budgie-remix/budgie-remix-welcome#8]
future enhancement:

  this option is not applicable for a live CD - lets hide it.

**Comment by niyasc** [comment]
I often think about it and forgets when I sit to code :grimacing: . It is just about adding `.normal-session-only` class.

**Comment by fossfreedom** [comment]
actually - I'll test this later - it was just something that struck me when looking at the pictures in the README.

**Comment by niyasc** [comment]
Pictures are not updated to indicate progress made in last few days.

**Comment by niyasc** [comment]
Tested and working as expected on budgie-remix 16.04
